<?php
	header('Content-Type: text/html; charset=utf-8');

	echo "<h1>this is generated by php script</h1>";
	
	echo "<h2>test get method and query string : </h2>";
	
	print_r($_GET);
	
	echo "<h2>test post method and post fileds : </h2>";
	
	print_r($_POST);

?>
